### PR TITLE
Fixing app label missing from pods

### PR DESCRIPTION
**Pull request by zdannar**
Adding 'app' lace as lacework agent name to pods.

### CODE REVIEW

**Comment by afiune** [comment]
make it so! 💯

**Comment by afiune** [comment]
Thank you @zdannar for your contribution! 💯  We are reviewing this change but in the meantime,
would you mind signing your commit? 

docs: https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification/signing-commits

**Review by rnalexlacework — APPROVED** [review]

**Review by afiune — APPROVED** [review]
tenor-153954198

**Comment by afiune** [comment]
@zdannar I see you are trying to sign your commit, we see progress but the status now says `Unverified`,
could you try to fix it following these instructions? 

https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification/displaying-verification-statuses-for-all-of-your-commits

**Comment by zdannar** [comment]
@afiune I was hoping to not publish my personal email.  So I used the zdannar@users.noreply method that github suggests.  Looks like you guys are wanting full verification so I will have to resign and verify with an email.

**Comment by afiune** [comment]
@zdannar I can understand your desire to keep your personal email private, I did a quick google search and found this, let me know if that works for you: https://superuser.com/questions/1512137/which-email-to-sign-commits-with-for-github-and-retain-privacy

**Comment by zdannar** [comment]
I found the noreply email in my github profile... Trying to update the signing key.  This should be good now... Looking further.

**Comment by zdannar** [comment]
Closing... Going to work out the signature from ground zero.

**Comment by afiune** [comment]
Superseded by https://github.com/lacework/terraform-kubernetes-agent/pull/24

**Pull request closed without merging**
